### ISSUE TITLE
Haladó JS kiinduló projekt

### ISSUE THREAD

**Issue by asztrikx** [VIAUAC00/laborok#44]
Számomra a jelenlegi beállításokkal a bable nem akart lefordulni, a következő módosításokat kellett végrehajtanom:
```
"babel-core": "^6.26.3",     -> "@babel/core": "^7.20.2",
"babel-loader": "^8.2.5",   -> "babel-loader": "^9.1.0",
"babel-preset-env": "^1.7.0",  -> "@babel/preset-env": "^7.20.2",
```
```
presets: ['env']  -> presets: ["@babel/preset-env"]
```
A backend szintén hibás volt, se a firefox, se a chrome nem tudtja hibás cert miatt a wss üzeneteket kijelezni, így a `websocket.js`-ben wss- ről ws-re kell átírni a protokollt, illetve `applicationUrl`-ben https-ről http-re

A backendben szintén van egy apró hiba, ami mindig ugyanazt a random számot sorsolja, a Randomize fgv a következőre írtam át:
```
public int Randomize()
{
    int random = _random.Next(1, 100);
    _currentValue = random;
    return random;
}
```

[Itt](https://github.com/VIAUAC00/web-lab-2022-js-advanced-asztrikx/commits/megoldas) láthatóak a változtatások.

**Comment by tibitoth** [comment]
Ez szerintem nem általánosan rossz (annak ellenére, hogy valóban régiek a csomagok). Nekem Windows-on VS-ben futtatva a BE-et jól működik a HTTPS, és a FE is simán lefordul `npm i` és `npm start` parancsokkal. 

Érdemes lenne külön beszélnünk róla, hogy nálad mi csúszott el, mert gyanúsnak tűnik a launch.json és a tasks.json a repódban.

A random jogos.

**Comment by tibitoth** [comment]
A kiindulót javítottam
