### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by hallabalint** [VIAUAC00/laborok#61]
Olyan hibát találtam (ehhez nem tudok Pull Requestet nyitni), hogy a github-classroom által kiadott laborokban a `.github/pull_request_template.md` fájlban a linkek hibásan szerepelnek. 

> A folyamatot részletesen lásd itt: https://bmeviauac01.github.io/laborok/GitHub/
>Please refer to the detailed guide here: https://bmeviauac01.github.io/laboratories-en/GitHub/

A helyes link
https://viauac00.github.io/laborok/tudnivalok/github/GitHub/

**Comment by tibitoth** [comment]
@hallabalint Köszi, javítottam őket. Természetesen a már lemásolt repókban nem tudom egyszerűen átírni, csak az új létrehozásakor lesz helyesen.
